name: explainability
channels:
  - conda-forge   
  - defaults
dependencies:
  - python=3.9
  - scikit-learn
  - matplotlib
  - numpy
  - graphviz
  - pip
  - jupyter       # or ipython, if you prefer interactive shells
  - dtreeviz      # provided by conda-forge
  # If dtreeviz wasn't found on conda-forge for some reason, you can fallback:
  # - pip:
  #   - dtreeviz
